### ISSUE TITLE
no hidden billing addres

### ISSUE THREAD

**Issue by Fernandito12** [xmpie-users/uStore-js#4]
i used this script and the billing address capture window is not hidden.
can you help me, please?
i contacted with XMPIE's support but they cant help me with you script.

PLEASE!!!

**Comment by scouch1** [comment]
Sorry that I missed this issue. 
I just checked the code on this page:
https://github.com/xmpie-users/uStore-js/wiki/Hiding-the-billing-address-if-it-is-already-entered
and it worked correctly in the current v13.1 uStore.
Since there were no other comments, I suspect you fixed the problem, so I will close the issue now.
